# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:               Francisco Zambrano Bigiarini
#tagline:             'foo's website
description:         Francisco Zambrano's blog...
url: https://frzambra.github.io/
baseurl: ""
urlimg: https://frzambra.github.io/images/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png 
safe: false
#timezone:    America/Chicago
future:      true

gems:
  - jekyll-paginate
  - jemoji
  - font-awesome-sass
  - kramdown
  - rouge

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name:              Francisco Zambrano
  url:               https://twitter.com/frzambra
  avatar:         foo.png
  #email:           

# Owner/author information
owner:
  name:           Foo Boo
  avatar:         foo.png
  #email:          
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        frzambra
  facebook:       
  github:         frzambra
  stackexchange:  
  linkedin:       https://www.linkedin.com/in/frzambra
  instagram:      
  flickr:
  tumblr:  
  google_plus:    https://plus.google.com/+frzambra
  # orcid and google scholar IDs are different than standard username.
  orcid:  0000-0001-6896-8534 
  gscholar: xyz123abc

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
  - title: <i class="iconside iconm-wordpress"></i> Old Blog
    url: https://r-recursos-naturales.blogspot.com/
    external: true
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-twitter"></i> Twitter
    url: https://twitter.com/frzambra
    external: true
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml

# Google Custom Search:
google_search: 002642212482439923032:bdda2imeoa4

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
twitter_widget_id: 730135969593098240

# Add disqus username for Disqus comment board:
disqus_shortname: frzambraBlog

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-64677575-1

#### For dummy website only - remove if you wish ####
github_repo: https://frzambra.github.io/frzambra
version: 1.1.0
## END ##

            