project:
  type: website
  output-dir: docs

website:
  title: "Francisco Zambrano"
  favicon: img/fzb_selfie.ico
  site-url: "https://francisco-zambrano.com"
  open-graph: true
  navbar:
    background: "#234460"
    left:
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects
      # - href: about.qmd
      #   text: About
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/frzambra/
      - icon: github
        href: https://www.github.com/frzambra
    

format:
  html:
    theme:
      - tango
      - rjh.scss
    toc: true
    mainfont: "Merriweather, Georgia, serif"
    html-math-method: katex
    include-in-header:
      file: header.html
