---
title: "About me"
---

## Bio

>**Francisco Zambrano** is a researcher based in Santiago, Chile. His work focuses on environmental sciences, particularly the intersection of climate variability, drought monitoring, and water resource management. I specialize in using remote sensing, geospatial analysis, and climate data to understand how environmental changes impact ecosystems and agriculture.
He hold a doctorate in agricultural engineer and have published extensively on topics such as vegetation dynamics, long-term drought assessments, and land use change. His research has been cited widely and contributes to both academic knowledge and practical decision-making in climate resilience and sustainable land management.
Whether through scientific publications, collaborative projects, or open-source development, He aim to bridge the gap between data, science, and policy to support more informed environmental decisions.

<!-- ## Address -->

<!-- **Mail:** [Hemera Centro de Observación de la Tierra](https://hemera.umayor.cl/), [Universidad Mayor](https://umayor.cl/), Santiago, Chile. -->

<!-- **Office:** Campus Oriente, [Universidad Mayor](https://umayor.cl/), Av. Apoquindo 6901-6947, 7570008 Las Condes, Región Metropolitana, Chile. -->

<!-- <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5737.456669745213!2d-70.56030748702727!3d-33.40793509522815!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662cec241761341%3A0xf601ad71e2d186c4!2sCampus%20Oriente%20Universidad%20Mayor!5e1!3m2!1ses-419!2scl!4v1754057780120!5m2!1ses-419!2scl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> -->

