---
title: "Prediction of agricultural drought in Chile from multiple spatio-temporal data sources"
author: "Zambrano et al."
year: "2018"
publication: "AGU Fall Meeting 2018"
materials: "https://ui.adsabs.harvard.edu/abs/2018AGUFMGC51H0882Z/abstract"
toc: false
categories:
  - verbal
  - article
---

## Citation (APA 7)

>  Zambrano, F., Vrieling, A., Nelson, A., Meroni, M., & Tadesse, T. (2018). Prediction of agricultural drought in Chile from multiple spatio-temporal data sources. 2018, GC51H-0882. https://ui.adsabs.harvard.edu/abs/2018AGUFMGC51H0882Z

 

## Abstract

 Global food security is negatively affected by drought. Climate projections show that drought frequency and intensity may increase in different parts of the globe. Early season forecasts on drought occurrence and severity could help to better mitigate the negative consequences of drought. The objective of this study was to assess if interannual variability in agricultural productivity in Chile can be accurately predicted from freely-available, near real-time data sources. As the response variable, we used the standard score of seasonal cumulative NDVI (zcNDVI), based on 2000-2017 data from Moderate Resolution Imaging Spectroradiometer (MODIS), as a proxy for anomalies of seasonal primary productivity. The predictions were performed with forecast lead-times from one- to six-month before the end of the growing season, which varied between census units in Chile. Predictor variables included the zcNDVI obtained by cumulating NDVI from season start up to prediction time; standardised precipitation indices, derived from satellite rainfall estimates, for time-scales of 1, 3, 6, 12 and 24 months; the Pacific Decadal Oscillation and the Multivariate ENSO oscillation indices; the length of the growing season, and latitude and longitude. We used two prediction approaches: (i) optimal linear regression (OLR) whereby for each census unit the single predictor was selected that best explained the interannual zcNDVI variability, and (ii) a multi-layer feedforward neural network architecture, often called deep learning (DL), where all predictors for all units were combined in a single spatio-temporal model. Both approaches were evaluated with a leave-one-year-out cross-validation procedure. Both methods showed good prediction accuracies for small lead times and similar values for all lead times. The mean R2cv values for OLR were 0.95, 0.83, 0.68, 0.56, 0.46 and 0.37, against 0.96, 0.84, 0.65, 0.54, 0.46 and 0.38 for DL, for one, two, three, four, five, and six months lead time, respectively. Given the wide range of climates and vegetation types covered within the study area, we expect that the presented models can contribute to an improved early warning system for agricultural drought in different geographical settings around the globe. 
