---
title: " The response of Groundwater-Dependent Ecosystems to drought in central Chile "
author: "Duran-Llacer et al."
year: "2024"
publication: "EGU General Assembly 2024"
doi: "https://doi.org/10.5194/egusphere-egu24-20738"
materials: "https://meetingorganizer.copernicus.org/EGU24/EGU24-20738.html"
toc: false
categories:
  - verbal
  - article
---

## Citation (APA 7)

>  Duran-Llacer, I., Zambrano, F., Gómez-Escalonilla Canales, V., Martínez Santos, P., Aliagada Alvarado, M., Rodríguez-López, L., Martínez-Retureta, R., and Arumí, J. L.: The response of Groundwater-Dependent Ecosystems to drought in central Chile, EGU General Assembly 2024, Vienna, Austria, 14–19 Apr 2024, EGU24-20738, https://doi.org/10.5194/egusphere-egu24-20738, 2024. 

## Abstract

Drought is considered the main climate limitation that affects the hydrological cycle, agriculture, people, and ecosystems. Since 2010, central Chile has been experiencing an uninterrupted sequence of dry years that has been classified as a megadrought, which has conditioned major social problems. This problem can't only affect agriculture, people, and access to drinking water in Chilean basins, but it can also affect the ecological integrity of ecosystems, particularly those known as groundwater-dependent ecosystems (GDE). The main objective of this research is to examine the relationship between groundwater-dependent ecosystems and drought using satellite data in the Aconcagua basin in central Chile.

Standardized Precipitation Index (SPI), Standardized Evapotranspiration Index (SPEI), Normalized Difference Vegetation Index (NDVI) and Land Surface Temperature (LST) were calculated to analyses relationship between groundwater-dependent ecosystem and drought. In addition, these parameters were analysed throughout the basin. To obtain and process these indicators between the years 2002 and 2022, the Google Earth Engine platform and the R environment were used. Subsequently, statistical analysis of the time series was performed, including Pearson correlation, Mann Kendall test, and Sen slope estimator. The results show that the SPI-SPEI at 12-24 months had a moderate correlation with the NDVI in much of the basin (>4) and high in the GDEs (>0.5). The slope of the Sen was more pronounced in the GDE zones, and the trend was decreasing with respect to the NDVI. LST and SPEI increased in the GDEs. In conclusion, the GDE zones were affected by drought processes, which demonstrates the need for sustainable management of these important ecosystems.