---
title: "Influence of Avocado Plantations as Driver of Land Use and Land Cover Change in Chile’s Aconcagua Basin"
type: "article"
author: "Dura-Llacer et al."
year: "2025"
publication: "Land"
doi: "https://doi.org/10.3390/land14040750"
#materials: "https://osf.io/sfhm2/"
toc: false
categories:
  - verbal
  - article
---

## Citation (APA 7)

> Duran-Llacer, I., Salazar, A. A., Mondaca, P., Rodríguez-López, L., Martínez-Retureta, R., Zambrano, F., Llanos, F., & Frappart, F. (2025). Influence of Avocado Plantations as Driver of Land Use and Land Cover Change in Chile’s Aconcagua Basin. Land, 14(4), 750. https://doi.org/10.3390/land14040750 

## Abstract

 Land use and land cover (LULC) change is a dynamic process influenced by various factors, including agricultural expansion. In Chile’s Aconcagua Basin, avocado plantations are potentially driving territorial transformations. However, current land cover data lacks the resolution required to accurately assess this impact. Accordingly, our study used advanced geospatial analysis techniques to address this gap. Through a detailed analysis of the spatial and temporal changes, it was determined that the most significant expansion of avocado plantations occurred between 2003 and 2013, with an increase of 402%. This growth primarily took place at the expense of native vegetation, particularly sclerophyllous shrubland, as well as other agricultural lands, near agricultural and urban lands. By 2023, changes in avocado plantation were significantly slower, with minimal alterations in LULC (5%), suggesting a possible influence of drought on small-scale farmers. However, the small loss of avocado plantation was mainly replaced by fruit farm land. Moreover, our findings suggest that while avocado plantations have become larger, more dominant, and more isolated, native vegetation has become more fragmented and reduced in patch size. Based on these results, sustainable land management practices were proposed. These findings provide a crucial foundation for developing sustainable land management strategies that balance agricultural production with environmental sustainability, landscape transformation and the well-being of local communities.
