---
title: "From Drought to Aridification: Land-cover fingerprints of a drying Chile"
type: "article"
author: "Zambrano et al."
year: "2025"
publication: "Earth's Future (AGU)"
#doi: "https://doi.org/10.1016/j.agwat.2025.109721"
#materials: "https://osf.io/sfhm2/"
toc: false
categories:
  - verbal
  - article
---

## Citation (APA 7)

> Zambrano, F., Vrieling, A., Meza, F., Duran-Llacer, I., Fernández, F., Venegas-González, A., Raab, N., Craven, D. (2025). From Drought to Aridification: Land-cover fingerprints of a drying Chile. Earth's Future (AGU). Under revision


## Abstract

Chile has endured a decade-long “mega-drought”, yet it remains unclear whether this represents a temporary climate anomaly or the onset of long-term aridification. While droughts are typically temporary events, persistent or recurrent droughts can indicate a transition toward aridification, i.e., a gradual shift to drier conditions. We assessed how temporal changes in water supply and demand at multiple time scales affect vegetation productivity and land cover changes in continental Chile to diagnose the region’s climate trajectory from drought to aridification. Since 2000, much of the region has seen a continuous decrease in water supply alongside a rise in atmospheric water demand. Further, in water-limited ecoregions, evapotranspiration, likely reflecting reduced transpiration or vegetation cover, has declined over time, with this trend intensifying over longer time scales. A long-term decline in water availability and shifting demand have led to declining vegetation productivity, especially in the Chilean Matorral and the Valdivian temperate forest ecoregions. We found that drought indices related to soil moisture and actual evapotranspiration at time scales of up to 12 months primarily explain these declines. Further, our results indicate that the trends in drought indices account for up to 78% of shrubland and 40% of forest area changes across all ecoregions. The most important variable explaining cropland changes is the burned area. Our findings suggest that Chile is undergoing a transition from episodic drought to aridification, underscoring the need for adaptation strategies aligned with this emerging baseline.

