---
title: "Evaluating satellite-derived long-term historical precipitation datasets for drought monitoring in Chile"
author: "Zambrano et al."
year: "2017"
publication: "Atmospheric Research"
doi: "https://doi.org/10.1016/j.atmosres.2016.11.006"
materials: "https://www.sciencedirect.com/science/article/abs/pii/S0169809516305865?via%3Dihub"
toc: false
categories:
  - verbal
  - article
---

## Citation (APA 7)

> Zambrano, F., Wardlow, B., Tadesse, T., Lillo-Saavedra, M., & Lagos, O. (2017). Evaluating satellite-derived long-term historical precipitation datasets for drought monitoring in Chile. Atmospheric Research, 186, 26–42. https://doi.org/10.1016/j.atmosres.2016.11.006

## Abstract

Precipitation is a key parameter for the study of climate change and variability and the detection and monitoring of natural disaster such as drought. Precipitation datasets that accurately capture the amount and spatial variability of rainfall is critical for drought monitoring and a wide range of other climate applications. This is challenging in many parts of the world, which often have a limited number of weather stations and/or historical data records. Satellite-derived precipitation products offer a viable alternative with several remotely sensed precipitation datasets now available with long historical data records (+30years), which include the Climate Hazards Group InfraRed Precipitation with Station (CHIRPS) and Precipitation Estimation from Remotely Sensed Information using Artificial Neural Networks-Climate Data Record (PERSIANN-CDR) datasets. This study presents a comparative analysis of three historical satellite-based precipitation datasets that include Tropical Rainfall Measuring Mission (TRMM) Multi-satellite Precipitation Analysis (TMPA) 3B43 version 7 (1998–2015), PERSIANN-CDR (1983–2015) and CHIRPS 2.0 (1981–2015) over Chile to assess their performance across the country and for the case of the two long-term products the applicability for agricultural drought were evaluated when used in the calculation of commonly used drought indicator as the Standardized Precipitation Index (SPI). In this analysis, 278 weather stations of in situ rainfall measurements across Chile were initially compared to the satellite data. The study area (Chile) was divided into five latitudinal zones: North, North-Central, Central, South-Central and South to determine if there were a regional difference among these satellite products, and nine statistics were used to evaluate their performance to estimate the amount and spatial distribution of historical rainfall across Chile. Hierarchical cluster analysis, k-means and singular value decomposition were used to analyze these datasets to better understand their similarities and differences in characterizing rainfall patterns across Chile. Monthly analysis showed that all satellite products highly overestimated rainfall in the arid North zone. However, there were no major difference between all three products from North to South-Central zones. Though, in the South zone, PERSIANN-CDR shows the lowest fit with high underestimation, while CHIRPS 2.0 and TMPA 3B43 v7 had better agreement with in situ measurements. The accuracy of satellite products were highly dependent on the amount of monthly rainfall with the best results found during winter seasons and in zones (Central to South) with higher amounts of precipitation. PERSIANN-CDR and CHIRPS 2.0 were used to derive SPI at time-scale of 1, 3 and 6 months, both satellite products presented similar results when it was compared in situ against satellite SPI's. Because of its higher spatial resolution that allows better characterizing of spatial variation in precipitation pattern, the CHIRPS 2.0 was used to mapping the SPI-3 over Chile. The results of this study show that in order to use the CHIRPS 2.0 and PERSIANN-CDR datasets in Chile to monitor spatial patterns in the rainfall and drought intensity conditions, these products should be calibrated to adjust for the overestimation/underestimation of rainfall geographically specially in the North zone and seasonally during the summer and spring months in the other zones.
