---
title: " Drought's trends over continental Chile using climatic variables of water demand and supply, soil moisture, and vegetation productivity"
author: "Zambrano et al."
year: "2024"
publication: "EGU General Assembly 2024"
doi: "https://doi.org/10.5194/egusphere-egu24-19099"
materials: "https://meetingorganizer.copernicus.org/EGU24/EGU24-19099.html"
toc: false
categories:
  - verbal
  - article
---

## Citation (APA 7)

>  Zambrano, F., Meza, F., Raab, N., and Duran-Llacer, I.: Drought’s trends over continental Chile using climatic variables of water demand and supply, soil moisture, and vegetation productivity, EGU General Assembly 2024, Vienna, Austria, 14–19 Apr 2024, EGU24-19099, https://doi.org/10.5194/egusphere-egu24-19099, 2024. 




## Abstract

Estimating the actual evapotranspiration of a crop (ET) is essential to determining the availability of water that plants need for proper growth. For this, remote sensors have an important role since they allow obtaining the daily ET of the crops. This research presents the estimate of ET, calculated using data from the Sentinel-2 and Sentinel-3 satellites, ERA-5 reanalysis data, land cover, and the Digital Elevation Model. For this, we used the algorithm Sen-ET. The ET was estimated in the five main orchards regarding the surface planted in the Aconcagua’s river basin (avocado, walnut, mandarin, grape vine, and peach). The period of time analyzed was from September 2022 to May 2023. We evaluate the spatio-temporal variation and calculate the total ET for the season per crop. Avocados reach the highest ET with 114.6 mm/season. The rest of the crops had between 95.4% and 83.3% of the demand for avocado. This study is the first approach to using sen-ET to evaluate the water requirements of crops in Chile. We need to advance further to improve the input data used (e.g., landcover) and validate the results.
